Set Token Permissions (#50)

diff --git a/.github/workflows/static-code-analysis.yaml b/.github/workflows/static-code-analysis.yaml
--- a/.github/workflows/static-code-analysis.yaml
+++ b/.github/workflows/static-code-analysis.yaml
@@ -3,39 +3,42 @@ name: Static Code Analysis
 on:
   workflow_call:
 
+permissions:
+  contents: read
+
 jobs:
-    static-code-analysis:
-        runs-on: ubuntu-latest
-        steps:
-            - name: Checkout code
-              uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
+  static-code-analysis:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
 
-            - name: DevSkim Security Analysis
-              run: |
-                dotnet tool install -g Microsoft.CST.DevSkim.CLI
-                devskim analyze --source-code ${{ github.workspace }}/src --output-file ${{ github.workspace }}/devskim-results.sarif -f sarif
+      - name: DevSkim Security Analysis
+        run: |
+          dotnet tool install -g Microsoft.CST.DevSkim.CLI
+          devskim analyze --source-code ${{ github.workspace }}/src --output-file ${{ github.workspace }}/devskim-results.sarif -f sarif
 
-            - name: Publish DevSkim Security Analysis Results
-              uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
-              if: always()
-              with:
-                name: CodeAnalysisLogs
-                path: ${{ github.workspace }}/devskim-results.sarif
+      - name: Publish DevSkim Security Analysis Results
+        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
+        if: always()
+        with:
+          name: CodeAnalysisLogs
+          path: ${{ github.workspace }}/devskim-results.sarif
 
-            - name: Fail If Critical or Important Severity Found
-              run: |
-                if grep -q -E '("DevSkimSeverity":"Critical"|"DevSkimSeverity":"Important")' ${{ github.workspace }}/devskim-results.sarif; then
-                  echo "Critical or Important severity found in devskim-results.sarif. Failing the pipeline."
-                  exit 1
-                fi
+      - name: Fail If Critical or Important Severity Found
+        run: |
+          if grep -q -E '("DevSkimSeverity":"Critical"|"DevSkimSeverity":"Important")' ${{ github.workspace }}/devskim-results.sarif; then
+            echo "Critical or Important severity found in devskim-results.sarif. Failing the pipeline."
+            exit 1
+          fi
 
-            - name: Set up Python
-              uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
-              with:
-                  python-version: '3.x'
+      - name: Set up Python
+        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
+        with:
+            python-version: '3.x'
 
-            - name: Install pre-commit
-              run: python -m pip install -r ./pre-commit-requirements.txt --no-deps
+      - name: Install pre-commit
+        run: python -m pip install -r ./pre-commit-requirements.txt --no-deps
 
-            - name: Run pre-commit checks
-              run: pre-commit run --all-files --show-diff-on-failure
+      - name: Run pre-commit checks
+        run: pre-commit run --all-files --show-diff-on-failure
